/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdint.h>

#define ALIAS_BASE     0x22000000U
#define BIT_BAND_BASE  0x20000000U

int main(void)
{
	uint8_t *ptr = (uint8_t *)0x20000200;

	*ptr = 0xff;

	// normal method
	// clearing 7th bit position
	*ptr &= ~(1 << 7);

	// Reset to 0xff
	*ptr = 0xff;

	// Bit Band Method
	//   Alias address  = alias_base + (32 * (bit_band_memory_addr - bit_band_base)) + bit * 4;
	uint8_t* alias_addr = (uint8_t *)(ALIAS_BASE + (32 * (0x20000200 - BIT_BAND_BASE)) + 7 * 4);

	// Clearing the 7th bit of address 0x20000200
	*alias_addr = 0;

	for(;;);
}
