/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include<stdio.h>
#include<stdint.h>

int main(void)
{
	__asm ("SVC #25");

	//register uint32_t data __asm("r0");  // r0 is the data variable

	uint32_t data;

	__asm volatile("MOV %0, R0" : "=r"(data) ::);

	printf(" data = %ld\n", data);

	for(;;);
}


__attribute__ ((naked)) void SVC_Handler(void)
{
	// 1. get the value of MSP

	__asm ("MRS r0, MSP");
	__asm ("B SVC_Handler_c");  // r0 goes to the 1st argument of the callee function, i.e., - pBaseOfStackFrame
}

void SVC_Handler_c(uint32_t *pBaseOfStackFrame)
{
	printf("in SVC handler\n");

	uint8_t *pReturn_addr = (uint8_t *) pBaseOfStackFrame[6];

	// 2. decrement the return address by 2 to point to
	// opcode of the SVC instruction in the program memory
	pReturn_addr  -= 2;

	// 3. extract the SVC number (LSByte of the opcode)
	uint8_t svc_number = *pReturn_addr;

	printf("SVC Number is: %d\n", svc_number);

	svc_number += 4;
	pBaseOfStackFrame[0] = svc_number;  // pBaseOfStackFrame[0] = r0 in stack frame
}

